version: '3'

services:
  node-app-img:
      build:
        context: .
        target: production
        # args:
        #   - NODE_ENV=production
      environment:
        - NODE_ENV=production
      command: npm start

