version: '3'

services:

  # mongo:
  #   image: mongo
  #   restart: always
  #   volumes:
  #     - mongo-db:/data/db
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example

  node-app-img:
    container_name: node-app-container
    image: emanabdelhamed241/nodejs-app
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    # depends_on:
      # - mongo
  
  redis: 
    image: redis

  
  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  #     ME_CONFIG_BASICAUTH: false

  nginx:
    image: nginx:stable-alpine
    volumes:
     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
     - "80:80"
    depends_on:
      - node-app-img
    #  environment:
    #  - NGINX_HOST=foobar.com
    #  - NGINX_PORT=80

# volumes:
  # mongo-db:
